name: Run Scraper

on:
  workflow_dispatch:  # Triggered by cron or manually

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Private Repo
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
        run: |
          git clone https://x-access-token:${PAT_GITHUB}@github.com/iamCristYE/QiQi.git
          cd QiQi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          cd QiQi
          pip install requests

      - name: Run Scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          cd QiQi
          python main.py

      - name: Commit and Push Changes
        run: |
          cd QiQi
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update sent IDs - $(date)"
            git push
          else
            echo "No changes to commit"
          fi